{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "timesliceorchestrator.fullname" . }}
  labels:
    {{- include "timesliceorchestrator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "timesliceorchestrator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "timesliceorchestrator.serviceAccountName" . }}
    namespace: timeslice-system
{{- end }}
